constrained_ik_solver:
  manipulator:
    allow_joint_convergence: false
    allow_primary_normalization: true
    allow_auxiliary_nomalization: true
    limit_primary_motion: true
    limit_auxiliary_motion: true
    limit_auxiliary_interations: false
    solver_max_iterations: 100
    solver_min_iterations: 0
    auxiliary_max_iterations: 5
    auxiliary_max_motion: 0.5
    primary_max_motion: 2.0
    primary_norm: 1.0
    auxiliary_norm: 0.15
    primary_gain: 1.0
    auxiliary_gain: 1.0
    joint_convergence_tol: 0.0001
    constraints:
    -
      class: constrained_ik/GoalToolPointing
      primary: true
      position_tolerance: 0.001
      orientation_tolerance: 0.009
      weights: [1, 1, 1, 1, 1]
    -
      class: constrained_ik/AvoidObstacles
      primary: false
      link_names:         [   link_2,   link_3,  link_4,    link_5,   link_6]
      amplitude:          [ 0.000001, 0.000001, 0.000001, 0.000001, 0.000001]
      minimum_distance:   [    0.001,     0.01,     0.01,     0.01,     0.01]
      avoidance_distance: [      0.1,      0.1,      0.1,      0.1,      0.1]
      weight:             [        1,        1,        1,        1,        1]
  manipulator_rail:
    allow_joint_convergence: false
    allow_primary_normalization: true
    allow_auxiliary_nomalization: true
    limit_primary_motion: true
    limit_auxiliary_motion: true
    limit_auxiliary_interations: false
    solver_max_iterations: 100
    solver_min_iterations: 0
    auxiliary_max_iterations: 5
    auxiliary_max_motion: 0.5
    primary_max_motion: 2.0
    primary_norm: 1.0
    auxiliary_norm: 0.15
    primary_gain: 1.0
    auxiliary_gain: 1.0
    joint_convergence_tol: 0.0001
    constraints:
    -
      class: constrained_ik/GoalToolPointing
      primary: true
      position_tolerance: 0.001
      orientation_tolerance: 0.009
      weights: [1, 1, 1, 1, 1]
    -
      class: constrained_ik/AvoidObstacles
      primary: false
      link_names:         [   link_2,   link_3,  link_4,    link_5,   link_6]
      amplitude:          [ 0.000001, 0.000001, 0.000001, 0.000001, 0.000001]
      minimum_distance:   [    0.001,     0.01,     0.01,     0.01,     0.01]
      avoidance_distance: [      0.1,      0.1,      0.1,      0.1,      0.1]
      weight:             [        1,        1,        1,        1,        1]
  manipulator_tool:
    allow_joint_convergence: false
    allow_primary_normalization: true
    allow_auxiliary_nomalization: true
    limit_primary_motion: true
    limit_auxiliary_motion: true
    limit_auxiliary_interations: false
    solver_max_iterations: 100
    solver_min_iterations: 0
    auxiliary_max_iterations: 5
    auxiliary_max_motion: 0.5
    primary_max_motion: 2.0
    primary_norm: 1.0
    auxiliary_norm: 0.15
    primary_gain: 1.0
    auxiliary_gain: 1.0
    joint_convergence_tol: 0.0001
    constraints:
    -
      class: constrained_ik/GoalToolPointing
      primary: true
      position_tolerance: 0.001
      orientation_tolerance: 0.009
      weights: [1, 1, 1, 1, 1]
    -
      class: constrained_ik/AvoidObstacles
      primary: false
      link_names:         [   link_2,   link_3,  link_4,    link_5,   link_6]
      amplitude:          [ 0.000001, 0.000001, 0.000001, 0.000001, 0.000001]
      minimum_distance:   [    0.001,     0.01,     0.01,     0.01,     0.01]
      avoidance_distance: [      0.1,      0.1,      0.1,      0.1,      0.1]
      weight:             [        1,        1,        1,        1,        1]


constrained_ik_planner:
  translational_discretization_step: 0.025
  orientational_discretization_step: 0.025
  joint_discretization_step: 0.02
