controller_list:
  - name: fake_manipulator_controller
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
  - name: fake_eef_controller
    joints:
      []
  - name: fake_manipulator_rail_controller
    joints:
      - rail_to_base
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
  - name: fake_manipulator_tool_controller
    joints:
      - rail_to_base
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6